### ISSUE TITLE
Mojo::Home::rel_dir is deprecated in MojoX::Renderer::Xslate::_init 

### ISSUE THREAD

**Issue by takkyuuplayer** [gray/mojox-renderer-xslate#7]
```
Mojo::Home::rel_dir is DEPRECATED in favor of Mojo::Home::rel_file
```

ref) https://github.com/kraih/mojo/blob/d5e61cec802e146f8e978d309969aefae061365a/lib/Mojo/Home.pm#L59-L64

They are in use at `MojoX::Renderer::Xslate::_init`

https://github.com/gray/mojox-renderer-xslate/blob/a1c47a92dc40ddb804fa250932462c6c77a64e2e/lib/MojoX/Renderer/Xslate.pm#L27-L30

Shall I replace it with `Mojo::Home::rel_file` and send you a pull request?

**Comment by heikojansen** [comment]
We certainly need to take on the deprecation, but I didn´t have time to evaluate the backward compatibility of a modified `MojoX::Renderer::Xslate` with older `Mojolicious` releases.

`Mojo::Home` already had a `rel_file` method prior to v7.14 and at first glance replacing `rel_dir` with `rel_file` should probably be compatible with `Mojolicious` <= v7.13 so we might not need to update the required `Mojolicious` version.

`Mojolicious` v7.15 further modified the `rel_file` method to return an object (with overloaded stringification op) instead of a plain string.

Would be good to know if everything works with both `Mojolicious` >= v7.15 and < v7.14 after replacing `rel_dir` with `rel_file`. Could you test that?

**Comment by takkyuuplayer** [comment]
> Would be good to know if everything works with both Mojolicious >= v7.15 and < v7.14 after replacing rel_dir with rel_file. Could you test that?

I tested and it worked. https://github.com/takkyuuplayer/mojox-renderer-xslate/pull/1

Mojolicious versions are

```
Mojolicious-7.18
Mojolicious-5.81
```

Shall I send a commit https://github.com/takkyuuplayer/mojox-renderer-xslate/pull/1/commits/73a3b2a914ff559349ad9ff3a013d7d727a7d805 as a pull request to you?

**Comment by heikojansen** [comment]
Sorry, I´m a bit on the slow side lately. 
Yes, please send a pr.
Also, since I like the idea and since my credentials seem to be sufficient for travis to pick up the repo I´d be interested in a second pr for the travis config you added.

**Comment by takkyuuplayer** [comment]
> Yes, please send a pr.

I created here https://github.com/gray/mojox-renderer-xslate/pull/9

> Also, since I like the idea and since my credentials seem to be sufficient for travis to pick up the repo I´d be interested in a second pr for the travis config you added.

Do you mean you want me to include https://github.com/takkyuuplayer/mojox-renderer-xslate/pull/1/commits/e4f046229605688bbe01c61f8a96cc5dc607644f into the pull request and you'll set travis up with your credentials? If so, I'll update my pull-request.

**Comment by heikojansen** [comment]
Yes - although I´d prefer a separate pull-request for the travis setup and thus have already merged pull-request #9

**Comment by takkyuuplayer** [comment]
Please check a pull-request https://github.com/gray/mojox-renderer-xslate/pull/10 for travis

**Comment by heikojansen** [comment]
Merged. 
Unfortunately it looks like I misunderstood travis-ci.org and cannot directly enable CI testing for this repo due to insufficient rights. I´d have sworn I saw the repo in some "activate here" list... Well, we´ll work something out.
I believe this issue can be closed now. I´ll send a new release to CPAN in the next few days. Thanks again for your contribution!

**Comment by takkyuuplayer** [comment]
Thank you! I'll wait new release to CPAN.

**Comment by takkyuuplayer** [comment]
Hi, @heikojansen 

> I´ll send a new release to CPAN in the next few days.

How is the progress?
